GET https://scorr-redeploy.herokuapp.com/pipelines2
Authorization: Bearer CMPco9KFMRIMAAEAAAAAAAAAAAAQGKeu-hIgsrjkFyi8imcyFHZwJlo7sHFPGH7SLZ3fToHIv97pOjAAAABBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAFCFKb-w3sHWzb92ZPYTnaDCpPeGZsLSgNuYTFSAFoAß